version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mybase  # Updated to your database name
      MYSQL_USER: mariabase    # Updated to match your user
      MYSQL_PASSWORD: P@55      # Updated to match your password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: url_shortener_app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://192.168.1.4:3306/mybase  # Updated to your database
      SPRING_DATASOURCE_USERNAME: mariabase                        # Updated to your user
      SPRING_DATASOURCE_PASSWORD: P@55                              # Updated to your password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MariaDBDialect
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

volumes:
  db_data:
